
utils::globalVariables(c("% Adult Height",
                         "%PAH",
                         "Age",
                         "Age * Leg Length",
                         "Age * Sitting Height",
                         "Age * Weight",
                         "Age @ PHV (Fransen)",
                         "Age @ PHV (Mirwald)",
                         "Age Group @ Testing",
                         "Age2",
                         "Athlete.fact",
                         "B1",
                         "B2",
                         "Bench Height (CM)",
                         "Biological Age",
                         "Birth Year",
                         "Column2",
                         "Current Age",
                         "Days Btwn Tests",
                         "DOB",
                         "Difference",
                         "Error (CM)",
                         "Error (IN)",
                         "Estimated Adult Height (CM)",
                         "Estimated Adult Height (FT'IN\")",
                         "Estimated Adult Height (IN)",
                         "Estimated Remaining Growth (CM)",
                         "Estimated Remaining Growth (FT'IN\")",
                         "Estimated Remaining Growth (IN)",
                         "F-Adult Height Attained",
                         "F-Height",
                         "F-Midparent Stature",
                         "F-Standard Deviation",
                         "F-Weight",
                         "Fathers Height (CM)",
                         "Fransen APHV",
                         "Fransen MO (years)",
                         "Fransen Ratio",
                         "Gender",
                         "Growth (CM)",
                         "Growth (IN)",
                         "Growth Velocity (cm/yr)",
                         "Growth Velocity (in/yr)",
                         "Height (cm)",
                         "Height (CM)",
                         "Height (FT'IN\")",
                         "Height (IN)",
                         "Height1 (CM)",
                         "Height2 (CM)",
                         "Height3 (CM)",
                         "L (Power)",
                         "Leg Length (CM)",
                         "Leg Length * Sitting Height",
                         "M (Median)",
                         "M-Adult Height Attained",
                         "M-Height",
                         "M-Midparent Stature",
                         "M-Standard Deviation",
                         "M-Weight",
                         "Maturity Timing (%AH)",
                         "Metric",
                         "Mirwald MO (years)",
                         "Mothers Height (CM)",
                         "P10",
                         "P25",
                         "P3",
                         "P5",
                         "P50",
                         "P75",
                         "P90",
                         "P95",
                         "P97",
                         "Parent Mid Height (CM)",
                         "Parent Mid Height (IN)",
                         "PHV Phase",
                         "Player Name",
                         "Quarter",
                         "ref",
                         "ref_pct_mean",
                         "ref_pctah",
                         "S (CV)",
                         "Sitting Height (CM)",
                         "Sitting Height1 (CM)",
                         "Sitting Height2 (CM)",
                         "Sitting Height3 (CM)",
                         "Testing Date",
                         "Type",
                         "Value",
                         "W-H Ratio",
                         "Weight (KG)",
                         "Weight (LB)",
                         "Weight1 (KG)",
                         "Weight2 (KG)",
                         "Weight3 (KG)",
                         "Weight Diff. (KG)",
                         "Weight Diff. (LB)",
                         "Weight Velocity (kg/yr)",
                         "Weight Velocity (lb/yr)",
                         "Z-Score",
                         "across",
                         "approx",
                         "desc",
                         "everything",
                         "lag",
                         "na.omit",
                         "rainbow",
                         "reorder",
                         "vars"))
